CITIES = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "San Francisco",
    "Charlotte",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington D.C.",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Long Beach",
    "Virginia Beach",
    "Miami",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "New Orleans",
    "Wichita",
    "Boise",
    "Durham",
    "Bakersfield",
    "Amarillo",
    "Corpus Christi",
    "Santa Fe",
    "Henderson",
    "Boca Raton",
    "Hartford",
    "Providence",
    "Pittsburgh",
    "Cincinnati",
    "Cleveland",
    "Des Moines",
    "Sioux Falls",
    "Billings",
    "Spokane",
    "Tacoma",
    "Eugene",
    "Stockton",
    "Pasadena",
    "Boulder",
    "Little Rock",
    "St. Louis",
    "Green Bay",
    "Glendale",
    "Charleston",
    "Jersey City",
    "Buffalo",
    "Rochester",
    "Toronto",
    "Winnipeg",
    "Quebec City",
    "Montreal",
    "Calgary",
    "Vancouver",
    "Edmonton",
    "Ottawa",
    "Anaheim",
    "Arlington",
    "Waco",
    "Salt Lake City",
    "Reno",
    "St. Paul" ,
    "Madison",
    "Jefferson City",
    "Lincoln",
    "Grand Rapids",
    "Fort Wayne",
    "Savannah",
    "Montgomery",
    "Birmingham",
    "New Orleans",
    "Baton Rouge",
    "Jackson",
    "Biloxi",
    "Chattanooga",
    "Knoxville",
    "Lexington",
    "Shreveport",
    "Huntsville",
    "Concord",
    "Wilmington",
    "Columbia",
    "Fargo",
    "Laramie",
    "Honolulu",
    "Anchorage"







]