# Sample names for random selection
FIRST_NAMES = [
    "Aaron", "Abel", "Abraham", "Adam", "Adrian", "Aiden", "Alessandro", "Alex", "Alfonso", "Alfredo",
    "Allen", "Alvin", "Amos", "Andre", "Anders", "Andrew", "Andy", "Angelo", "Anthony", "Anton",
    "Archie", "Armando", "Arturo", "Asher", "Augustus", "Axel", "Barney", "Barry", "Ben", "Bennett",
    "Benson", "Bill", "Billy", "Blaine", "Blake", "Bob", "Bobby", "Brad", "Brandon", "Brayden",
    "Brett", "Brian", "Brody", "Bruce", "Bryant", "Bryce", "Cal", "Calvin", "Camden", "Carl",
    "Carlos", "Carmine", "Carson", "Carter", "Casey", "Cecil", "Cesar", "Chad", "Chandler", "Chance",
    "Charles", "Charlie", "Chester", "Chris", "Clarence", "Clark", "Clay", "Cliff", "Cody", "Colin",
    "Conrad", "Connor", "Cornelius", "Craig", "Cyrus", "Curtis", "Damien", "Dan", "Dante", "Darnell",
    "Darren", "Daryl", "Dave", "David", "Dean", "Dennis", "Derek", "Desmond", "Devin", "Dexter",
    "Dillon", "Dobson", "Dominic", "Don", "Donnie", "Doug", "Drew", "Duncan", "Dustin", "Dwight",
    "Dylan", "Earl", "Eddie", "Edgar", "Edison", "Edward", "Eli", "Elias", "Elijah", "Elmer",
    "Elliot", "Elton", "Emilio", "Emmett", "Enrique", "Eric", "Esteban", "Ethan", "Eugene", "Evan",
    "Everett", "Ezekiel", "Fabian", "Felix", "Fernando", "Finn", "Fletcher", "Floyd", "Francisco", "Frank",
    "Franklin", "Fred", "Fredrick", "Gabriel", "Garrett", "Gary", "Gavin", "Gene", "Geoffrey", "George",
    "Gerald", "Gian", "Gilbert", "Giovanni", "Glenn", "Gordon", "Graham", "Grady", "Grant", "Greg",
    "Gregory", "Griffin", "Gunner", "Hamilton", "Harold", "Harris", "Harrison", "Harry", "Harvey", "Hayden",
    "Hector", "Henry", "Howard", "Hugh", "Hudson", "Hunter", "Ian", "Isaac", "Isaiah", "Ivan",
    "Jack", "Jackson", "Jacob", "Jace", "Jake", "Jamal", "James", "Jared", "Jason", "Jasper",
    "Javier", "Jay", "Jeff", "Jeffrey", "Jeremiah", "Jeremy", "Joaquin", "Joel", "John", "Johnny",
    "Jon", "Jonas", "Jonathan", "Jordan", "Joseph", "Josh", "Joshua", "Juan", "Judson", "Julian",
    "Justin", "Kaden", "Keith", "Keegan", "Ken", "Kendrick", "Kenneth", "Kevin", "Kingston", "Kirk",
    "Kris", "Kyle", "Lance", "Landon", "Larry", "Lawrence", "Leland", "Leo", "Leon", "Leonard",
    "Leroy", "Liam", "Lionel", "Logan", "Louis", "Lucas", "Luis", "Luke", "Malcolm", "Malik",
    "Marc", "Marcus", "Manuel", "Marquis", "Marshall", "Martin", "Mason", "Matt", "Matthew", "Maurice",
    "Mauricio", "Max", "Melvin", "Michael", "Mickey", "Miguel", "Mike", "Miles", "Mitchell", "Monte",
    "Morgan", "Nash", "Nathan", "Nathaniel", "Neal", "Nelson", "Neil", "Nicholas", "Nick", "Nolan",
    "Norman", "Oliver", "Orlando", "Oscar", "Owen", "Patrick", "Paul", "Perry", "Peter", "Philip",
    "Phillip", "Preston", "Quentin", "Quincy", "Ralph", "Randall", "Randy", "Raphael", "Ray", "Raymond",
    "Reed", "Reginald", "Rex", "Richard", "Rick", "Ricky", "Rob", "Robert", "Robin", "Roderick",
    "Rodney", "Roger", "Roland", "Ron", "Ronald", "Ross", "Roy", "Rugrat", "Russell", "Ryan",
    "Sam", "Samuel", "Santiago", "Scott", "Sean", "Seth", "Shane", "Shaun", "Sidney", "Sleve",
    "Spencer", "Stanley", "Stephen", "Steve", "Stewart", "Stogard", "Ted", "Terrence", "Terry", "Theo",
    "Theodore", "Thomas", "Tim", "Timothy", "Todd", "Tobias", "Tom", "Tony", "Travis", "Trent",
    "Trevor", "Troy", "Tyler", "Tyson", "Vance", "Vernon", "Victor", "Vincent", "Wade", "Walter",
    "Warren", "Wayne", "Wesley", "Weston", "Wilbur", "William", "Willie", "Wilson", "Wyatt", "Xander",
    "Xavier", "Yale", "Yancy", "Zach", "Zachary", "Zander", "Zane"
]


LAST_NAMES = [
    "Abbott", "Abrams", "Adams", "Alvarez", "Allen", "Anderson", "Archideld", "Armstrong", "Austin", "Bailey", 
    "Baldwin", "Baker", "Barker", "Barner", "Barnes", "Baxter", "Beck", "Bell", "Bennett", "Black", 
    "Blake", "Boone", "Bonzales", "Bowman", "Boyd", "Bradley", "Brady", "Briggs", "Brooks", "Brown", 
    "Bryant", "Burns", "Burton", "Butler", "Caldwell", "Cameron", "Campbell", "Canseco", "Carter", "Casey", 
    "Chambers", "Chandler", "Chapman", "Chavez", "Christensen", "Clark", "Clayton", "Cobb", "Collins", "Conner", 
    "Conway", "Cook", "Cooper", "Cox", "Cristobal", "Cunningham", "Dalton", "Davis", "Delgado", "Dennis", "Diaz", 
    "Dixon", "Doyle", "Drake", "Dudley", "Dugnutt", "Duncan", "Edwards", "Elliott", "Ellis", "Erickson", 
    "Estrada", "Evans", "Farmer", "Ferguson", "Fitzgerald", "Fleming", "Flores", "Ford", "Foster", "Franklin", 
    "Freeman", "Gallegos", "Galloway", "Garcia", "Gates", "Gentry", "Gibbs", "Gilbert", "Gill", "Gonzalez", 
    "Goodwin", "Gray", "Green", "Griffin", "Hall", "Hancock", "Harding", "Harmon", "Harris", "Henderson", 
    "Hernandez", "Hickman", "Higgins", "Hill", "Hoffman", "Holland", "Hooper", "Horne", "Howard", "Hubbard", 
    "Hughes", "Ingram", "Jackson", "James", "Jarvis", "Jefferson", "Jenkins", "Johnson", "Jones", "Joyner", 
    "Kaiser", "Kane", "Kelly", "King", "Klein", "Knox", "Lamb", "Larsen", "Lawson", "Lee", 
    "Leonard", "Lewis", "Lindsay", "Lopez", "Madden", "Maddox", "Mahoney", "Marsh", "Martin", "Martinez", 
    "Massey", "Maynard", "McCall", "McDichael", "McKinney", "Mercer", "Meyers", "Miller", "Mitchell", "Moore", 
    "Morales", "Morgan", "Morris", "Morrow", "Nelson", "Neal", "Nguyen", "Ochoa", "Osborne", "Palacios", 
    "Parker", "Patagonia", "Patrick", "Perez", "Perry", "Peterson", "Phillips", "Powell", "Price", "Ramirez", 
    "Reed", "Ricardo", "Richardson", "Rickard", "Rivera", "Roberts", "Robinson", "Rodriguez", "Rogers", "Ross", 
    "Runce", "Russell", "Sanchez", "Sanders", "Scott", "Sernandez", "Smith", "Stewart", "Taylor", "Thomas", 
    "Thompson", "Torres", "Turner", "Walker", "Ward", "Warner", "Washington", "Watkins", "Watson", "Wedge", 
    "White", "Williams", "Wilson", "Wood", "Wright", "Young", "Zamora", "Zavala", "Zimmerman"
]
