STADIUM_NAMES = [
    "Titan Field",
    "RexTech Stadium",
    "Victory Park",
    "Champion Grounds",
    "Innovate Field",
    "Glacier Dome",
    "Summit Stadium",
    "Ironclad Park",
    "Thunderbolt Grounds",
    "Diamond Point Stadium",
    "Pinnacle Field",
    "Edgewater Park",
    "Solaris Grounds",
    "Horizon Stadium",
    "Legion Field",
    "Velocity Park",
    "Founders Stadium",
    "Skyline Grounds",
    "Blackstone Field",
    "Rising Sun Park",
    "Harborview Stadium",
    "Falcon Ridge Grounds",
    "Skyfire Field",
    "Stormwatch Stadium",
    "Bluewave Park",
    "Cobalt Grounds",
    "Legacy Field",
    "Summerset Stadium",
    "Gritstone Park",
    "Beacon Grounds",
    "Pioneers Field",
    "Vanguard Stadium",
    "Eagle's Nest Park",
    "Crystal Peak Grounds",
    "Ironforge Stadium",
    "Majestic Field",
    "Sierra View Park",
    "Silverstone Stadium",
    "Goldrush Grounds",
    "Redwood Field",
    "Liberty Park",
    "Crestfield Stadium",
    "Oakwood Grounds",
    "Vortex Stadium",
    "Northstar Park",
    "Quantum Field",
    "Oasis Grounds",
    "Crescent Ridge Stadium",
    "Trophy Park"
]