TEAM_MASCOTS = [
    "Thunder Roosters",
    "Wild Wolves",
    "Flaming Phoenixes",
    "Electric Eagles",
    "Rampaging Rhinos",
    "Batty Bats",
    "Scorching Scorpions",
    "Ice Panthers",
    "Majestic Lions",
    "Daring Dolphins",
    "Steel Stallions",
    "Savage Sharks",
    "Booming Bison",
    "Flying Falcons",
    "Stormy Tigers",
    "Howling Huskies",
    "Fiery Falcons",
    "Fearless Firehawks",
    "Sneaky Snakes",
    "Blazing Bulls",
    "Soaring Owls",
    "Mighty Mantas",
    "Vicious Vultures",
    "Raging Rhinos",
    "Galloping Gazelles",
    "Roaring Raptors",
    "Cunning Coyotes",
    "Raging Bulls",
    "Rampant Jaguars",
    "Stealthy Cheetahs",
    "Battle Badgers",
    "Charging Chargers",
    "Wrathful Wolves",
    "Thunderous Tigers",
    "Rising Raccoons",
    "Bold Beavers",
    "Fierce Foxes",
    "Swift Swallows",
    "Dashing Dingo",
    "Mighty Moles",
    "Pouncing Pumas",
    "Valiant Vipers",
    "Grizzly Griffins",
    "Power Penguins",
    "Lightning Lynxes",
    "Wild Wolverines",
    "Unstoppable Unicorns",
    "Flashing Falcons",
    "Storm Surge",
    "Titans",
    "Blizzards",
    "Vanguards",
    "Rangers",
    "Rebels",
    "Warlords",
    "Gremlins",
    "Red Pandas",
    "Rocket Fuel",
    "Blast",
    "Saints",
    "Bakers",
    "Iron Forge",
    "Freeze",
    "Swashbucklers",
    "Mountain Climbers",
    "Sailing Squirrels",
    "Skunks", 
    "Armadillos", 
    "Geckos", 
    "Komodo Dragons", 
    "Hissing Serpents", 
    "Wizards",
    "Senators", 
    "Metros", 
    "Lumberjacks",
    "Sailors",
    "Spiders",
    "Axolotl", 
    "Pufferfish",
    "Starfish",
    "Squids",
    "Fighting Crabs", 
    "Turtles", 
    "Goats",
    "Hogs",
    "Buffalo",
    "Galloping Antelope",
    "Mechanics",
    "Gold Rush",
    "Miners",
    "Rockers",
    "Spin-City"
]